name = "reader-tts-api"
main = "src/index.ts"
compatibility_date = "2026-06-29"

[vars]
APP_NAME = "reader-tts"
GEMINI_TTS_MODEL = "gemini-2.5-flash-preview-tts"

[[d1_databases]]
binding = "DB"
database_name = "reader_tts"
database_id = "c58a5509-40d7-439a-8bfb-42b8d990a245"

[[r2_buckets]]
binding = "AUDIO_CACHE"
bucket_name = "reader-tts-audio-cache"
