from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parent
WEB_DIST = ROOT / "web-next" / "dist"
PUBLIC_DIR = ROOT / "public"


# Cloudflare Worker API for the SPA. Always inject at build time so production
# never calls same-origin /api on Vercel (legacy Python → "Authentication required.").
DEFAULT_VITE_API_ORIGIN = "https://reader-tts-api.reader-tts-ari.workers.dev"


def main() -> None:
    shutil.rmtree(PUBLIC_DIR, ignore_errors=True)
    npm_command = "npm.cmd" if os.name == "nt" else "npm"

    build_env = os.environ.copy()
    # Empty string in the Vercel dashboard would still win — treat it as unset.
    raw = (build_env.get("VITE_API_ORIGIN") or "").strip()
    api_origin = (raw if raw else DEFAULT_VITE_API_ORIGIN).rstrip("/")
    build_env["VITE_API_ORIGIN"] = api_origin
    # Always write .env.production so Vite mode=production loads it reliably.
    env_file = ROOT / "web-next" / ".env.production"
    env_file.write_text(
        "# Generated by vercel_build.py — do not rely on local secrets here.\n"
        f"VITE_API_ORIGIN={api_origin}\n",
        encoding="utf-8",
    )
    print(f"[vercel_build] VITE_API_ORIGIN={api_origin}", flush=True)

    subprocess.run(
        [npm_command, "--prefix", "web-next", "run", "build"],
        cwd=ROOT,
        check=True,
        env=build_env,
    )
    if not WEB_DIST.exists():
        raise FileNotFoundError(f"Expected built frontend at {WEB_DIST}")
    shutil.copytree(WEB_DIST, PUBLIC_DIR)

    # WASM files are large (~22 MB for ort-wasm-simd-threaded) and served by the
    # Vercel CDN from outputDirectory (web-next/dist). The Python lambda never reads
    # them; keeping them in public/ sweeps them into the 245 MB lambda bundle cap.
    for wasm in PUBLIC_DIR.rglob("*.wasm"):
        wasm.unlink()

    # Vercel bundles the entire project tree into the Python serverless function
    # AFTER install + build. Anything left on disk counts toward the 245 MB cap.
    # None of the following directories are needed by the Python runtime:
    #   - web-next/node_modules  (~250 MB ONNX Runtime WASM + transformers.js)
    #   - web-next/src           (~0.5 MB TypeScript source, compiled into dist/)
    #   - web-next/e2e           Playwright tests
    #   - web-rewrite            legacy app, not deployed
    shutil.rmtree(ROOT / "web-next" / "node_modules", ignore_errors=True)
    shutil.rmtree(ROOT / "web-next" / "src", ignore_errors=True)
    shutil.rmtree(ROOT / "web-next" / "e2e", ignore_errors=True)
    shutil.rmtree(ROOT / "web-rewrite", ignore_errors=True)

    # package-lock.json is large (~400 KB) and only needed for npm ci, not at runtime
    (ROOT / "web-next" / "package-lock.json").unlink(missing_ok=True)


if __name__ == "__main__":
    main()
